### ISSUE TITLE
Error message using sDNA Prepare Network in qgis

### ISSUE THREAD

**Issue by albertpyyang** [fiftysevendegreesofrad/sdna_qgis_plugin#9]
I'm preparing a road network using the sDNA Prepare Network tool, and I get the following error message.

I running it on qgis 2.18.28, and my OS is Windows 10 64 bit.

```
Algorithm Prepare Network starting...
**********************************************************************
WARNING: sDNA ignores your selection and will process the entire layer
**********************************************************************
Running external command: "D:\Program Files\QGIS 2.18\bin\python.exe" "c:\Program Files (x86)\sDNA\bin\sdnaprepare.py" --im "net=D:/MEGAsync/lbm/nanjing_roads_project.shp" --om "net=D:/MEGAsync/lbm/qgis/sdna/nj_prepare.shp;errors=D:/MEGAsync/lbm/qgis/sdna/nj_prepare.shp" "start_gs=;end_gs=;xytol=;ztol=;action=REPAIR;nearmisses;duplicates;isolated;splitlinks;island=;data_absolute=;data_unitlength=;data_text="

sDNA sdnaprepare config: start_gs=;end_gs=;xytol=;ztol=;action=REPAIR;nearmisses;duplicates;isolated;splitlinks;island=;data_absolute=;data_unitlength=;data_text=
Loading DLL c:\Program Files (x86)\sDNA\\x64\\sdna_vs2008.dll
ERR: Traceback (most recent call last):
ERR:   File "c:\Program Files (x86)\sDNA\bin\sdnaprepare.py", line 4, in <module>
ERR:     commandline_integral_prepare("sdnaprepare")
ERR:   File "c:\Program Files (x86)\sDNA\commandline_integral_prepare.py", line 103, in commandline_integral_prepare
ERR:     dll = options.dll)
ERR:   File "c:\Program Files (x86)\sDNA\runcalculation.py", line 58, in runcalculation
ERR:     tablecollection1d = TableCollection()
ERR:   File "c:\Program Files (x86)\sDNA\sdnapy.py", line 215, in __init__
ERR:     self.dll=_dll()
ERR:   File "c:\Program Files (x86)\sDNA\sdnapy.py", line 38, in _dll
ERR:     __initialize_dll()
ERR:   File "c:\Program Files (x86)\sDNA\sdnapy.py", line 74, in __initialize_dll
ERR:     __dll_instance = windll.LoadLibrary(str(__sdna_dll_path))
ERR:   File "D:\Program Files\QGIS 2.18\apps\python27\Lib\ctypes\__init__.py", line 444, in LoadLibrary
ERR:     return self._dlltype(name)
ERR:   File "D:\Program Files\QGIS 2.18\apps\python27\Lib\ctypes\__init__.py", line 366, in __init__
ERR:     self._handle = _dlopen(self._name, mode)
ERR: WindowsError: [Error 14001] Ó¦ÓÃ³ÌÐòÎÞ·¨Æô¶¯£¬ÒòÎªÓ¦ÓÃ³ÌÐòµÄ²¢ÐÐÅäÖÃ²»ÕýÈ·¡£ÓÐ¹ØÏêÏ¸ÐÅÏ¢£¬Çë²ÎÔÄÓ¦ÓÃ³ÌÐòÊÂ¼þÈÕÖ¾£¬»òÊ¹ÓÃÃüÁîÐÐ sxstrace.exe
External command completed
ERROR: PROCESS DID NOT COMPLETE SUCCESSFULLY
Converting outputs
Loading resulting layers
Algorithm Prepare Network finished
```

Thanks for your help!

**Comment by fiftysevendegreesofrad** [comment]
Windows 10 is not officially supported. I suspect this bug is to do with side-by-side DLL configurations handled by ctypes in Windows 10. The bug is in the main sDNA software which will shortly be released as open source.
